---
    - name: Install and configure NTP
      yum:
        name: ntp
        state: present
      when: ansible_distribution == "CentOS"

    - name: Start and enable NTP service
      service:
        name: ntpd
        state: started
        enabled: true
      when: ansible_distribution == "CentOS"

